<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>etpl</string>
		<string>tpl</string>
		<string>text.html</string>
		<string>tpl.html</string>
	</array>
	<key>name</key>
	<string>ETPL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html-tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commands</key>
		<dict>
			<key>begin</key>
			<string>(&lt;!--)\s*(\/)?([a-z]+)\s*(:)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.command.begin.etpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.close.etpl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.etpl entity.name.command.etpl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.start.etpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(--&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.command.end.etpl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.command.etpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#func</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>&lt;!--\s*\/\/</string>
			<key>comment</key>
			<string>ETPL comments, like &lt;!-- // comments --&gt;</string>
			<key>contentName</key>
			<string>string.unquoted.comment.etpl</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.line.character.etpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid-comments</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>escaped-double-quote</key>
		<dict>
			<key>match</key>
			<string>\\\"</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
		<key>escaped-single-quote</key>
		<dict>
			<key>match</key>
			<string>\\\'</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
		<key>func</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9\_]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.etpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.etpl meta.brace.round.etpl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.etpl meta.brace.round.etpl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-in</string>
				</dict>
			</array>
		</dict>
		<key>html-tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9:-]+)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>&lt;tag&gt;&lt;/tag&gt;, &lt;x-component&gt;&lt;/x-component&gt;</string>
					<key>end</key>
					<string>(&gt;)(&lt;)(/)(\2)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html meta.scope.between-tag-pair.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;\?)(xml)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>&lt;?xml version="1.0" ?&gt;</string>
					<key>end</key>
					<string>(\?&gt;)</string>
					<key>name</key>
					<string>meta.tag.preprocessor.xml.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-generic-attribute</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>--\s*&gt;</string>
					<key>name</key>
					<string>comment.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#invalid-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commands</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>meta.tag.sgml.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?i:doctype)</string>
							<key>end</key>
							<string>(?=&gt;)</string>
							<key>name</key>
							<string>meta.tag.sgml.doctype.html</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\"[^"&gt;]*\"</string>
									<key>name</key>
									<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[CDATA\[</string>
							<key>end</key>
							<string>]](?=&gt;)</string>
							<key>name</key>
							<string>constant.other.inline-data.html</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#variables</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#commands</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(\s*)(?!--|&gt;)\S(\s*)</string>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.style.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
					<key>name</key>
					<string>source.css.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&gt;)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.html</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=&lt;/(?:style))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.css</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.js.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.begin.html</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.script.html</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(&lt;/)((?i:script))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(//).*?((?=&gt;/script)|$\n?)</string>
									<key>name</key>
									<string>comment.line.double-slash.js</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>/\*</string>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\*/|(?=&lt;/script)</string>
									<key>name</key>
									<string>comment.block.js</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:body|head|html)\b)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.structure.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.structure.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.block.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.inline.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((?: ?/)?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.inline.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.other.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.other.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;</string>
					<key>name</key>
					<string>invalid.illegal.incomplete.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;</string>
					<key>name</key>
					<string>invalid.illegal.bad-angle-bracket.html</string>
				</dict>
			</array>
		</dict>
		<key>invalid-comments</key>
		<dict>
			<key>match</key>
			<string>--</string>
			<key>name</key>
			<string>invalid.illegal.bad-comments-or-CDATA.html</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.etpl</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>meta.delimiter.comma.etpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>!|\$|%|&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|\.|\b(as)\b</string>
					<key>name</key>
					<string>keyword.operator.etpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[|\]</string>
					<key>name</key>
					<string>meta.brace.square.etpl</string>
				</dict>
			</array>
		</dict>
		<key>parameter-in</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z0-9_])+\b</string>
			<key>name</key>
			<string>variable.parameter.in.etpl</string>
		</dict>
		<key>pipeline</key>
		<dict>
			<key>match</key>
			<string>\s*\|\s*</string>
			<key>name</key>
			<string>keyword.control.pipeline.etpl</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.etpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped-double-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.etpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped-single-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commands</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>\'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#commands</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
			</array>
		</dict>
		<key>variable-in</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z0-9_])+\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.etpl variable.other.in.etpl</string>
		</dict>
		<key>variables</key>
		<dict>
			<key>begin</key>
			<string>(\$\{)\s*(\*?)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.variable.begin.etpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.raw.etpl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ETPL Variables, like ${name}, ${ data.name | raw }</string>
			<key>end</key>
			<string>\s*(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.variable.end.etpl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.other.etpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#func</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pipeline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-in</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.etpl</string>
	<key>uuid</key>
	<string>f8961911-529d-48e9-8fd2-58c5d733ae68</string>
</dict>
</plist>
